runtime: python37

env_variables:
  SECRET_KEY: "txohe%^&vgt!ej%1b7got1l2o+x4q2n)rf2bx#xoegm2uc%)a5"
  DEBUG: "False"
  DB_HOST: "/cloudsql/internbeat:us-central1:intern-production"
  DB_PORT: "5432" # PostgreSQL port
  DB_NAME: "django"
  DB_USER: "postgres"
  DB_PASSWORD: "ax15xf73zfHgF2Ks"
  DJANGO_SETTINGS_MODULE: "internapi.settings.production_settings"

beta_settings:
  cloud_sql_instances: internbeat:us-central1:intern-production
