version: "3"

services:
  db:
    image: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  elasticsearch:
    image: elasticsearch:2.4.2
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    ports:
      - "9300:9300"
      - "9200:9200"
  web:
    build: .
    command: gunicorn -b 0.0.0.0:8000 internapi.wsgi
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DB_PASSWORD=fjkdls
    depends_on:
      - db
      - elasticsearch
