version: "3"

services:
  db:
    build:
      context: .
      dockerfile: PostgresDockerfile
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --settings=internapi.settings.development_settings
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
