# Generated by Django 2.2.2 on 2019-07-02 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0007_auto_20190702_2052'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('salary_in_cents', models.BigIntegerField()),
                ('anonymous', models.BooleanField(default=True)),
                ('overall_rating', models.FloatField()),
                ('pay_period', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=5)),
                ('mentorship_rating', models.FloatField()),
                ('work_life_balance_rating', models.FloatField()),
                ('meaningful_work_rating', models.FloatField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
