# Generated by Django 2.2.2 on 2019-07-02 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='job_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobs.Job'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='salary_in_cents',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
