# Generated by Django 2.2.2 on 2019-07-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20190702_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
