# Generated by Django 2.2.2 on 2019-07-22 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20190722_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='job_id',
            new_name='job',
        ),
    ]
