# Generated by Django 2.2.2 on 2019-07-23 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20190722_2040'),
    ]

    operations = [
        migrations.RunSQL('CREATE INDEX "review_company_key" on "reviews_review" ("company_id")')
    ]
