# Generated by Django 2.2.2 on 2019-07-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('website_url', models.URLField(blank=True)),
                ('careers_url', models.URLField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('slug', models.CharField(max_length=50)),
                ('user_reviews_count', models.IntegerField(default=0)),
                ('total_rating', models.FloatField(blank=True)),
                ('avg_rating', models.FloatField(blank=True)),
                ('hq_city', models.CharField(blank=True, max_length=50)),
                ('hq_region', models.CharField(blank=True, max_length=50)),
                ('hq_country', models.CharField(blank=True, max_length=50)),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
