# Generated by Django 2.2.2 on 2019-07-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20190702_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='careers_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='total_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
