# Generated by Django 2.2.2 on 2019-07-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20190702_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='hq_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='hq_country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='hq_region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
