# Generated by Django 2.2.2 on 2019-07-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20190702_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='avg_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
