# Generated by Django 2.2.2 on 2019-07-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_auto_20190702_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='avg_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='company',
            name='total_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
