# Generated by Django 2.2.2 on 2019-07-02 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0007_auto_20190702_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('min_salary_in_cents', models.BigIntegerField(blank=True, null=True)),
                ('max_salary_in_cents', models.BigIntegerField(blank=True, null=True)),
                ('avg_salary_in_cents', models.BigIntegerField(blank=True, null=True)),
                ('avg_rating', models.FloatField(blank=True, null=True)),
                ('slug', models.CharField(max_length=75)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('total_rating', models.FloatField(blank=True, null=True)),
                ('total_salary_in_cents', models.BigIntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
