# Generated by Django 2.2.2 on 2019-07-23 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20190722_2000'),
    ]

    operations = [
        migrations.RunSQL('CREATE INDEX "job_company_key" on "jobs_job" ("company_id")'),
        migrations.RunSQL('CREATE INDEX "review_job_key" on "reviews_review" ("job_id")')
    ]
